name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run check script
        run: npm run check

      - name: Run lint script
        run: npm run lint

      - name: Run build script
        run: npm run build
